### PR TITLE
WIP: Issue #44 Python 3

### PR DESCRIPTION
**Pull request by dotsdl**
We want this library to work under both Python 3 and 2 (issue #44). I've started by running `2to3` on the whole `gromacs` module, and will troubleshoot each issue using feedback from the tests via Travis. Will remove WIP tag when finished.

### CODE REVIEW

**Comment by dotsdl** [comment]
We now have builds of gromacs conda packages for both gromacs 4.6.7 and gromacs 5.1.2 for python 3.5, but the thing that fails now is getting `recsql`, which [also doesn't work for python 3 yet](https://github.com/orbeckst/RecSQL/issues/5). I think we have at least two options:
1. Solve orbeckst/RecSQL#5 
2. Remove numkit (#82), which I believe is the only thing that really needs `recsql`?

What do you think we should do, @orbeckst?

**Comment by orbeckst** [comment]
Preferrably 1 and fix orbeckst/RecSQL#5... but the problem is not numkit, I think (where did you find recsql there??) but more likely gromacs.analysis.... and that we would like to split off in #82.

So I think from the GW perspective: solve #82 and this one solves itself...

**Comment by orbeckst** [comment]
We want to remain compatible with Python 2.7 for right now. Therefore, simple `2to3` is not good, for instance, we need to keep the `from __future__ import...`.  Perhaps `2to3` has options to remain compatible?

The testing matrix is good.

**Comment by orbeckst** [comment]
PR is superceded by PR #127

**Pull request closed without merging**
