### PR TITLE
fix cbook.portable_topology() for Python 2/3

### PR DESCRIPTION
**Pull request by orbeckst**
Fix the file writing and add a test.

### CODE REVIEW

**Comment by orbeckst** [comment]
@ALescoulie here is the test for the portable_topology() function.

I'll see if I can fix the actual error but if you have a quick solution the feel free to push to this branch/PR against the branch.

**Comment by orbeckst** [comment]
Locally the tests passed for me (in Python 3.6). Does it fail for you locally?

We need to get CI running again #200 ... I'll try to look at this later this morning.

**Comment by orbeckst** [comment]
@ALescoulie I don't really know what needs fixing here because the tests pass for all versions of Python without any errors in the cbook.portable_topology() test. Did you encounter the error on Linux or another OS?

(Locally, all tests also pass for me on macOS 10.15.7, Python 3.8)

**Comment by ALescoulie** [comment]
I noticed that the test passed which is strange, I ran my tests on linux on tubiwan. For some reason I got a TypeError passing kwargs into gromacs wrapper in MDPOW for them.

**Comment by orbeckst** [comment]
I add writing as binary as recommended in #199 ; I don't see any changes in the tests but perhaps your specific failure is now going away.

**Comment by orbeckst** [comment]
Can you try out this version of GW (install from the branch). 

The _review_ the PR. Add comments. If it works for you, you can also just approve it.

**Comment by ALescoulie** [comment]
I'll update package and try the tests again. I'm not sure why I repeatedly got that error, everything looked good in MDPOW, and I tried imputing some of the parameters separately.

**Review by ALescoulie — APPROVED** [review]
All the cbook tests passed when  I ran them.

**Comment by orbeckst** [comment]
Thanks @ALescoulie , hopefully it works for MDPOW, too.

**Pull request merged**
