### PR TITLE
Improvements to the TOP reader

### PR DESCRIPTION
**Pull request by jandom**

### CODE REVIEW

**Comment by orbeckst** [comment]
@jandom, sorry only saw this right now. General rule to get my attention: assign me as reviewer or do an @orbeckst in a comment to ping me.

Can you write a minimal test to go with this?

**Comment by jandom** [comment]
@orbeckst looking at this puppy now

**Comment by orbeckst** [comment]
Ping we when I should review.

**Comment by jandom** [comment]
@orbeckst i quite like the new style of tests and all - sane way of doing OO test. It's just hard for me to rip-out the intermediate state when it goes wrong, or at least keep the working directory from being cleaned-up - how does one work with these tests?

**Comment by orbeckst** [comment]
@dotsdl and @ianmkenney : have you got experience with debugging pytest tests with tempdir fixtures? How do you keep the directories around for post-mortem during debugging?

**Comment by dotsdl** [comment]
Yes. I'll have a look at this now. We do this everywhere in datreant, and pytest keeps the last three or so tmpdirs around for exactly this purpose.

**Comment by orbeckst** [comment]
@jandom why did you close this PR? Do you still need @dotsdl 's insights?

**Comment by jandom** [comment]
@orbeckst @dotsdl sorry this was accidental - i rebased my old branch on top of the current development branch, a new PR will follow - let's divide and conquer for now and try to close #61

**Pull request closed without merging**
