### PR TITLE
removed support for Python <= 3.7

### LINKED ISSUE #259: drop support for very old Python versions
GromacsWrapper has been supporting legacy Python for a long time (2.7, <3.7... arguable 3.7 and 3.8 are also old) and in principle we could continue to do so. However, it becomes increasingly complex to manage the testing of the old versions so we will **retire support for Python 2.7 and ~<3.7~ ≤3.7 in the next release**. 

GW 0.8.5 #256  is the last release that supports the full range of Python versions.

### PR DESCRIPTION
**Pull request by orbeckst**
- close #259 
- removed six and replaced with Python 3.x constructs
- updated package meta data
- update installation docs (sphinx and README)
- updated CHANGES

### CODE REVIEW

**Comment by orbeckst** [comment]
The macOS 3.11 GROMACS 2023.1 tests fail 

```
                :-) GROMACS - gmx mdrun, 2023.1-conda_forge (-:

Executable:   /Users/runner/micromamba/envs/test/bin.AVX2_256/gmx
Data prefix:  /Users/runner/micromamba/envs/test
Working dir:  /private/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/pytest-of-runner/pytest-0/1ake0/em
Command line:
  gmx mdrun -nt 2 -v -stepout 10 -deffnm em -c em.pdb


Back Off! I just backed up em.log to ./#em.log.1#

-------------------------------------------------------
Program:     gmx mdrun, version 2023.1-conda_forge
Source file: src/gromacs/hardware/printhardware.cpp (line 108)

Fatal error:
The gmx mdrun executable was compiled to use the rdtscp CPU instruction.
However, this is not supported by the current hardware and continuing would
lead to a crash. Please rebuild GROMACS with the GMX_USE_RDTSCP=OFF CMake
option.
```

It looks as if the conda-forge GROMACS package is incompatible with the run environment of GitHub. Not sure what to do...

**Comment by orbeckst** [comment]
Let's see if downgrading to conda-forge GROMACS 2022.4 for macOS helps.

**Comment by orbeckst** [comment]
After reading https://manual.gromacs.org/2021.3/release-notes/2021/major/portability.html#rdtscp-usage-and-reporting 
> GROMACS now defaults always on x86 to use the RDTSCP machine instruction for lower latency timing. Very old machines might need to configure with GMX_USE_RDTSCP=off. Non-x86 platforms are unaffected, except that they will no longer report that RDTSCP is disabled (because that is self-evident).

I am just trying out the [bioconda gromacs](https://anaconda.org/bioconda/gromacs/files) packages, maybe they are compiled differently??

**Comment by orbeckst** [comment]
didn't work

**Comment by orbeckst** [comment]
Previous successful macOS runners used
 + gromacs                        2021.1  nompi_h2eb4de6_102  bioconda        Cached
so I should try to get this version installed.

**Comment by orbeckst** [comment]
How the **** is this failing now when 

      + gromacs                        2021.1  nompi_h2eb4de6_102  bioconda        Cached

is being installed in the macOS 3.11 runner?

The same set up passed the tests previously https://github.com/Becksteinlab/GromacsWrapper/actions/runs/6211029287/job/16859829487 .

**Comment by orbeckst** [comment]
There are a few very minor Python package version changes (e.g. numpy 1.24 to 1.25). The image is different 20230901.1 (mac OS 12.6.8) vs 20230921.1 (mac OS 12.6.9). I just don't understand why any of this should matter for GROMACS.

## Failed test 
2023-11-08, this PR
```
2023-11-08T05:49:34.5156160Z Current runner version: '2.311.0'
2023-11-08T05:49:34.5185150Z ##[group]Operating System
2023-11-08T05:49:34.5185780Z macOS
2023-11-08T05:49:34.5186100Z 12.6.9
2023-11-08T05:49:34.5186410Z 21G726
2023-11-08T05:49:34.5186730Z ##[endgroup]
2023-11-08T05:49:34.5187100Z ##[group]Runner Image
2023-11-08T05:49:34.5187530Z Image: macos-12
2023-11-08T05:49:34.5187900Z Version: 20230921.1
2023-11-08T05:49:34.5189060Z Included Software: https://github.com/actions/runner-images/blob/macOS-12/20230921.1/images/macos/macos-12-Readme.md
2023-11-08T05:49:34.5190870Z Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230921.1
2023-11-08T05:49:34.5191930Z ##[endgroup]
2023-11-08T05:49:34.5192320Z ##[group]Runner Image Provisioner
2023-11-08T05:49:34.5192830Z 2.0.312.1
2023-11-08T05:49:34.5193160Z ##[endgroup]
```

## passed test

2023-09-17 , https://github.com/Becksteinlab/GromacsWrapper/actions/runs/6211029287/job/16859829487
```
2023-09-17T02:16:35.8965190Z Current runner version: '2.309.0'
2023-09-17T02:16:35.9006190Z ##[group]Operating System
2023-09-17T02:16:35.9006970Z macOS
2023-09-17T02:16:35.9007340Z 12.6.8
2023-09-17T02:16:35.9007660Z 21G725
2023-09-17T02:16:35.9008010Z ##[endgroup]
2023-09-17T02:16:35.9008330Z ##[group]Runner Image
2023-09-17T02:16:35.9008820Z Image: macos-12
2023-09-17T02:16:35.9009180Z Version: 20230901.1
2023-09-17T02:16:35.9009740Z Included Software: https://github.com/actions/runner-images/blob/macOS-12/20230901.1/images/macos/macos-12-Readme.md
2023-09-17T02:16:35.9010370Z Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230901.1
2023-09-17T02:16:35.9010930Z ##[endgroup]
2023-09-17T02:16:35.9011340Z ##[group]Runner Image Provisioner
2023-09-17T02:16:35.9011720Z 2.0.299.1
2023-09-17T02:16:35.9012010Z ##[endgroup]
```

**Comment by orbeckst** [comment]
I am reduced to trying out random GROMACS packages in the hope that _one_ works... :-(

**Comment by orbeckst** [comment]
Hooray 🎉 , the old GROMACS 2018.6 works on the macOS runners. I don't know why, but I'll take it...

**Review by jandom — APPROVED** [review]
Bye-bye legacy ware! Also nice adventure ripping this out – i enjoyed reading your mishaps above!

**Pull request merged**
