### PR TITLE
Fix file open

### PR DESCRIPTION
**Pull request by whitead**
Addresses #181

### CODE REVIEW

**Review by orbeckst — APPROVED** [review]
lgtm... will merge even if CI complains

**Review by orbeckst — CHANGES_REQUESTED** [review]
Could you please add an entry to CHANGES — it fixes a bug after all. Thanks.

**Comment by whitead** [comment]
@orbeckst Got it added

**Review by orbeckst — APPROVED** [review]

**Comment by orbeckst** [comment]
will squash-merge in a little bit, thanks @whitead !

**Pull request merged**
