### PR TITLE
fixed stop_logging() NameError

### LINKED ISSUE #211: stop_logging() fails with NameError
```python
In [24]: gromacs.stop_logging()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-24-6cc2d3cd56a5> in <module>
----> 1 gromacs.stop_logging()

~/.conda/envs/gw/lib/python3.8/site-packages/gromacs/__init__.py in stop_logging()
    233     from . import log
    234     logger = logging.getLogger("gromacs")
--> 235     logger.info("GromacsWrapper %s STOPPED logging", get_version())
    236     log.clear_handlers(logger)  # this _should_ do the job...
    237

NameError: name 'get_version' is not defined
```

### PR DESCRIPTION
**Pull request by orbeckst**
- fix #211
- add tests
- updated logger tests to use tmp_path
- updated CHANGES

### CODE REVIEW

**Review by ALescoulie — COMMENTED** [review]
Looks good. Glad logger tests are being added.

**Comment by orbeckst** [comment]
@ALescoulie are you able to approve the PR or did you only have the opportunity to comment?

If after looking at the code you think that the PR is ok, then _approve_. If you think that anything needs changing, _request changes_. Being blunt is much more helpful in code review than being diplomatic.

**Comment by orbeckst** [comment]
(Also, I can only merge without invoking admin powers when I get at least one approving review. I'd rather go through the process than to merge via admin.)

**Review by ALescoulie — APPROVED** [review]
Looks Good, sorry I forgot to switch it from comment to approve.

**Comment by orbeckst** [comment]
Thanks @ALescoulie !

**Pull request merged**
