### PR TITLE
Listconversion for MDP files

### PR DESCRIPTION
**Pull request by PicoCentauri**
Lists in MDP files will be converted into numpy arrays if autoconvert=True is set.
This enhancement can be useful for changing list parameters in the mdp file i.e. lambda states.

### CODE REVIEW

**Comment by PicoCentauri** [comment]
@orbeckst Sorry that I opened a new pull request, but I did not manage to fix to wrong branch including your previous pull requests...

I added a simple test case for the auto convert function. It would be nice to check the numpy type (dtype). I will look into this later. 

I will also tackle the mdp file test...

**Comment by orbeckst** [comment]
New branch is absolutely fine!

Will have a look.

**Comment by orbeckst** [comment]
Quick comment: also add an entry to CHANGES and add yourself to AUTHORS.

**Comment by PicoCentauri** [comment]
Done!

**Comment by orbeckst** [comment]
Thanks – and welcome as a contributor; I'll send you a GH invite in a moment.

**Pull request merged**
