### PR TITLE
Added a method to get MDP parameters as dict

### PR DESCRIPTION
**Pull request by whitead**
Wrote a small convenience method to read an MDP file and get a dictionary. 

Also, do we require unit tests yet for PRs? I haven't kept up on status of testing.

### CODE REVIEW

**Comment by whitead** [comment]
Just realized that there is an MDP file format class that can do what I need. Maybe this is redundant...

**Comment by orbeckst** [comment]
Did you check `fileformats.mdp.MDP`?  Does it do what you need or is it worthwhile merging your approach with `MDP`?

Finally, @pslacerda also has a pretty sleak MDP data structure in his [gmxscript](https://github.com/pslacerda/gmx) and I vaguely remember that at some point he was talking about porting it to GW.

Regarding tests: I am now trying to add more tests and certainly tests for new features are *very much encouraged* (and tests for old stuff will net you lots of good karma ;-) ).

**Comment by whitead** [comment]
Yeah, I realize now that the `MDP` class does everything I need. When I have some free time, I'll put a reference in the `cbook.edit_mdp` doc to the `MDP` fileformat. And maybe write some of these karma generating tests :+1:

**Comment by pslacerda** [comment]
What can a user want to do with a mdp file? The [sample.py][1] shows only part of what we can put on GromacsWrapper.

We can create something like the following hypothetical `mdp()` function: 

```python
# reads the file step.mdp
>>> mdp('step.mdp')
{'integrator': 'steep', 'emtol': 10}

# returns the path of a temporary file with parameters from step.mdp
# merged with user supplied ones.
>>> mdp('step.mdp', {
...  'rlist': 1.4,
...  'rcoulomb': 1.4,
...  'rvdw': 1.4
...  })
{'integrator': 'steep', 'emtol': 10, 'rlist': 1.4, 'rcoulomb': 1.4, 'rvdw': 1.4}

# returns the path of a temporary file created with these parameters
>>> mdp({'integrator': 'steep', 'emtol': 10, 'rlist': 1.4, 'rcoulomb': 1.4, 'rvdw': 1.4})
{'integrator': 'steep', 'emtol': 10, 'rlist': 1.4, 'rcoulomb': 1.4, 'rvdw': 1.4}

```

Okay, maybe three separated functions.

[class MDPResource][1] also features automatic lookup in parent directories: `mdp('mdp/step.mdp')` returns `mdp/step.mdp`, `../mdp/step.mdp`, `../../mdp/step.mdp`, or raise an exception if not found.

Tests are very very nice, but also very hard. There are some crazy people that likes it so much that tests before developing (ie TDD), they can think how the new artifact will look beforehand.

Hope we can achieve a neat and pleasurable tool for molecular dynamics.

[1]: https://github.com/pslacerda/gmx/blob/master/sample/sample.py
[2]: https://github.com/pslacerda/gmx/blob/master/gmxscript.py#L193

**Pull request closed without merging**
